### ISSUE TITLE
Beatmap files

### ISSUE THREAD

**Issue by HeyItzRaiderZ** [oamaok/oppai-web#2]
When I pick the map I want to calculate for pp, seems that some maps weren't shown. My osu! music folder has all the beatmaps I download, but when I look in the osu! music folder from oppai-web, some of the beatmaps were missing, even when searching it up, none of them showed up.

Plz fix. Ty

**Comment by oamaok** [comment]
This isn't a problem I can fix, I just use the browser's build in file selector (which is also the only option). Either you're searching them from the wrong place or something's up with your browser.
